# 应用环境
spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  config:
    import: classpath:secret.properties
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: 'tb_'
myapp:
  file-path: temporary/
  template-order-path: template/order.xlsx
  template-checkForm-path: template/checkForm.xlsx
