# 开发环境
spring:
  profiles: staging
  application:
    name: management
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${server.ip}:${mysql.port}/kwy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${db.username}
      password: ${db.password}
server:
  port: 82

logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d.%i.log
      max-history: 30
  level:
    root: info
  file:
    path: logs/